apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc1.name | default "test-claim" }}
spec:
  storageClassName: {{ .Values.pvc1.storageClassName | default "nfs-client" }}
  accessModes:
    - {{ .Values.pvc1.accessMode | default "ReadWriteMany" }}
  resources:
    requests:
      storage: {{ .Values.pvc1.storage | default "1Mi" }}
